FROM python:3.9

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Installiere System-Dependencies (inkl. JDK)
RUN apt-get update && apt-get install -y \
    default-jdk \
    curl \
    unzip \
    procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# AWS-Umgebungsvariablen (Achtung: für dev okay, aber nie Keys hardcoden!)
ENV AWS_ACCESS_KEY_ID="AKIAVUDEFQ2QWMOBCWXR"
ENV AWS_SECRET_ACCESS_KEY="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"
ENV AWS_DEFAULT_REGION=eu-north-1

# Python-Dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiere deinen Code ins Image
COPY . .

# Flask-Port freigeben
EXPOSE 3002

# Startbefehl
CMD ["python", "server.py"]
