FROM python:3.9-slim

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Installiere System-Dependencies (inkl. JDK)
RUN apt-get update && apt-get install -y \
    default-jdk \
    curl \
    unzip \
    procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

ENV AWS_DEFAULT_REGION=eu-north-1

# Python-Dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiere deinen Code ins Image
COPY . .

# Flask-Port freigeben
EXPOSE 3002

# Startbefehl
CMD ["python", "server.py"]
