apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsf-filter
  namespace: document-stream-filter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsf-filter
  template:
    metadata:
      labels:
        app: dsf-filter
    spec:
      containers:
      - name: dsf-filter
        image: 386757133985.dkr.ecr.eu-north-1.amazonaws.com/dsf-filter:latest
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: dsf-filter-service
  namespace: document-stream-filter
spec:
  selector:
    app: dsf-filter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer
