replicaCount: 2
image:
  repository: 386757133985.dkr.ecr.eu-north-1.amazonaws.com/dsf-website
  tag: latest
  pullPolicy: Always
service:
  name: dsf-website
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: REPLACE_HOST
      paths:
        - path: /website
          pathType: Prefix
          backend:
            service:
              name: dsf-website
              port:
                number: 80
serviceAccount:
  create: false
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
