replicaCount: 2
image:
  repository: 386757133985.dkr.ecr.eu-north-1.amazonaws.com/dsf-queries
  tag: latest
  pullPolicy: Always
service:
  name: dsf-queries
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: a98f16d1b90d54374a72e6a7a00b9494-582298901.eu-north-1.elb.amazonaws.com
      paths:
        - path: /queries
          pathType: Prefix
          backend:
            service:
              name: dsf-queries
              port:
                number: 80
serviceAccount:
  create: false
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
