name: CI/CD pipeline for docker image build
# This GitHub Actions workflow builds a Docker image for the document-stream-filter project and pushes it to the GitHub Container Registry.
# It is triggered on pushes to the main branch.
# The server downloads the image from the GitHub Container Registry by himself and runs it.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/document-stream-filter:latest ./webserver

      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CI_CD_ACCESS_TOKEN }}

      - name: push docker image to github container registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/document-stream-filter:latest


