name: CI/CD pipeline for docker image and deployment on EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/document-stream-filter:latest .

      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CI_CD_ACCESS_TOKEN }}

      - name: push docker image to github container registry
        run: |
          set -x  # Debugging aktivieren
          docker push ghcr.io/${{ github.repository_owner }}/document-stream-filter:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install SSH and docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh docker-compose

      - name: decode EC2 SSH Private Key
        run: |
          echo "${{secrets.EC2_SSH_SECRET_ACCESS_KEY}}" | base64 --decode > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@51.21.195.248 << 'EOF'
            echo "${{ secrets.CI_CD_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          
            sudo apt-get update
            sudo apt-get install -y docker.io

            sudo usermod -aG docker ubuntu
            newgrp docker

            docker pull ghcr.io/${{ github.repository_owner }}/document-stream-filter:latest
            docker stop document-stream-filter || true
            docker rm document-stream-filter || true
            docker run -d --name document-stream-filter -p 80:3000 ghcr.io/${{ github.repository_owner }}/document-stream-filter:latest
          EOF

